<script lang="ts">
  import { gzip } from 'pako';

  type Node = {
    type: 'prefix' | 'weight' | 'permission';
    key: string;
    value: boolean;
  };

  type Group = {
    name: string;
    prefix: string; // e.g. "prefix.1.&7&lMEMBER&r "
    weight?: number; // e.g. 100
    permissions: string[]; // e.g. ['essentials.fly']
  };

  let groups: Group[] = [
    { name: 'default', prefix: 'prefix.1.&7&lMEMBER&r ', weight: undefined, permissions: [] }
  ];

  let generatedBy = 'Scalamobile';

  function addGroup() {
    groups = [
      ...groups,
      { name: '', prefix: 'prefix.1.&7&lRANK&r ', weight: undefined, permissions: [] }
    ];
  }

  function removeGroup(idx: number) {
    groups = groups.filter((_, i) => i !== idx);
  }

  function addPermission(idx: number) {
    groups[idx].permissions = [...groups[idx].permissions, 'example.permission'];
  }

  function removePermission(gidx: number, pidx: number) {
    groups[gidx].permissions = groups[gidx].permissions.filter((_, i) => i !== pidx);
  }

  function nowPretty(): string {
    try {
      // Use local time with short TZ name, close to examples like "CEST"
      return new Date().toLocaleString(undefined, { hour12: false, timeZoneName: 'short' });
    } catch {
      return new Date().toISOString();
    }
  }

  function buildJsonPayload(emptyBase = false) {
    const metadata = {
      generatedBy,
      generatedAt: nowPretty()
    };

    if (emptyBase) {
      return {
        metadata,
        groups: {},
        tracks: {},
        users: {}
      };
    }

    const groupsObj: Record<string, { nodes: Node[] }> = {};

    for (const g of groups) {
      if (!g.name.trim()) continue;

      const nodes: Node[] = [];
      // prefix node expects full key like: prefix.1.&7&lMEMBER&r 
      if (g.prefix && g.prefix.trim()) {
        nodes.push({ type: 'prefix', key: g.prefix.trim(), value: true });
      }
      // weight node
      if (typeof g.weight === 'number' && Number.isFinite(g.weight)) {
        nodes.push({ type: 'weight', key: `weight.${g.weight}`, value: true });
      }
      // permissions
      for (const perm of g.permissions) {
        const p = (perm || '').trim();
        if (!p) continue;
        nodes.push({ type: 'permission', key: p, value: true });
      }

      groupsObj[g.name.trim()] = { nodes };
    }

    return {
      metadata,
      groups: groupsObj,
      tracks: {},
      users: {} // intentionally empty so the user can add on the LuckPerms editor site
    };
  }

  function downloadGz(filename: string, jsonObj: unknown) {
    const json = JSON.stringify(jsonObj, null, 2);
    const compressed = gzip(json);
    const blob = new Blob([compressed], { type: 'application/gzip' });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  function exportFilled() {
    const data = buildJsonPayload(false);
    downloadGz('luckperms.json.gz', data);
  }

  function exportEmptyBase() {
    const data = buildJsonPayload(true);
    downloadGz('luckperms-base.json.gz', data);
  }
</script>

<style>
  .card { border: 1px solid #333; border-radius: 8px; padding: 12px; margin: 8px 0; background: #111; }
  .row { display: flex; gap: 8px; flex-wrap: wrap; }
  .col { display: flex; flex-direction: column; gap: 6px; }
  input, textarea, select { background: #1b1b1b; color: #e0e0e0; border: 1px solid #333; border-radius: 6px; padding: 8px; }
  label { font-size: 0.9rem; color: #bbb; }
  button { background: #2d6cdf; color: white; border: none; border-radius: 6px; padding: 8px 12px; cursor: pointer; }
  button.secondary { background: #444; }
  button.danger { background: #d94a4a; }
  .muted { color: #8a8a8a; font-size: 0.9rem; }
</style>

<svelte:head>
  <title>LuckPerms Prefix/Groups Builder</title>
  <meta name="description" content="Crea gruppi LuckPerms con prefix, weight e permessi ed esporta in .json.gz" />
</svelte:head>

<div class="col" style="gap:12px">
  <h1>LuckPerms Prefix/Groups Builder</h1>
  <div class="row">
    <div class="col" style="flex:1; min-width:260px">
      <label>Generated by</label>
      <input bind:value={generatedBy} placeholder="Scalamobile" />
      <span class="muted">Verrà inserito in <code>metadata.generatedBy</code>.</span>
    </div>
  </div>

  <div class="row" style="align-items:center; gap:12px; margin-top:8px">
    <button on:click={addGroup}>+ Aggiungi gruppo</button>
    <button class="secondary" on:click={exportEmptyBase}>Esporta base vuota (.json.gz)</button>
    <button on:click={exportFilled}>Esporta con gruppi (.json.gz)</button>
  </div>

  {#each groups as g, i}
    <div class="card">
      <div class="row">
        <div class="col" style="flex:1; min-width:200px">
          <label>Nome gruppo</label>
          <input bind:value={g.name} placeholder="owner, admin, default, ..." />
        </div>
        <div class="col" style="flex:2; min-width:300px">
          <label>Prefix (chiave completa)</label>
          <input bind:value={g.prefix} placeholder="prefix.1.&7&lMEMBER&r " />
          <span class="muted">Usa la sintassi completa: <code>prefix.&lt;priorità&gt;.&lt;testo formattato&gt;</code></span>
        </div>
        <div class="col" style="width:160px">
          <label>Weight (numero)</label>
          <input type="number" bind:value={g.weight} placeholder="100" />
        </div>
      </div>

      <div class="col" style="margin-top:8px">
        <label>Permessi</label>
        {#each g.permissions as p, pidx}
          <div class="row" style="align-items:center">
            <input style="flex:1" bind:value={g.permissions[pidx]} placeholder="es. essentials.fly" />
            <button class="danger" on:click={() => removePermission(i, pidx)}>Rimuovi</button>
          </div>
        {/each}
        <div>
          <button class="secondary" on:click={() => addPermission(i)}>+ Aggiungi permesso</button>
        </div>
      </div>

      <div style="margin-top:8px">
        <button class="danger" on:click={() => removeGroup(i)}>Rimuovi gruppo</button>
      </div>
    </div>
  {/each}

  <div class="card">
    <h3>Formato di esportazione</h3>
    <pre class="muted" style="overflow:auto; max-height:240px">{JSON.stringify(buildJsonPayload(true), null, 2)}</pre>
    <span class="muted">La base esportata ha <code>groups</code> e <code>users</code> vuoti per essere compilata nel sito LuckPerms.</span>
  </div>
</div>
